/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FoodCategory = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Time = IDL.Int;
export const Inventory = IDL.Record({
  'id' : IDL.Principal,
  'quantityPurchased' : IDL.Float64,
  'remainingStock' : IDL.Float64,
  'unit' : IDL.Text,
  'updatedAt' : Time,
  'itemName' : IDL.Text,
  'quantityUsed' : IDL.Float64,
});
export const MessEntry = IDL.Record({
  'id' : IDL.Principal,
  'date' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'unit' : IDL.Text,
  'totalCost' : IDL.Float64,
  'pricePerUnit' : IDL.Float64,
  'itemName' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const Purchase = IDL.Record({
  'id' : IDL.Principal,
  'totalPurchase' : IDL.Float64,
  'supplier' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Time,
  'unit' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'itemName' : IDL.Text,
  'quantity' : IDL.Float64,
});
export const Setting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
export const StudentCount = IDL.Record({
  'id' : IDL.Principal,
  'date' : IDL.Text,
  'studentsOnLeave' : IDL.Nat,
  'createdAt' : Time,
  'totalStudents' : IDL.Nat,
  'studentsPresent' : IDL.Nat,
  'perStudentCost' : IDL.Float64,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'role' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFoodCategory' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Principal], []),
  'createInventory' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Principal],
      [],
    ),
  'createMessEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
      [IDL.Principal],
      [],
    ),
  'createPurchase' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
      [IDL.Principal],
      [],
    ),
  'createStudentCount' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [IDL.Principal],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Principal], []),
  'deleteFoodCategory' : IDL.Func([IDL.Principal], [], []),
  'deleteInventory' : IDL.Func([IDL.Principal], [], []),
  'deleteMessEntry' : IDL.Func([IDL.Principal], [], []),
  'deletePurchase' : IDL.Func([IDL.Principal], [], []),
  'deleteStudentCount' : IDL.Func([IDL.Principal], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getAllFoodCategories' : IDL.Func([], [IDL.Vec(FoodCategory)], ['query']),
  'getAllInventory' : IDL.Func([], [IDL.Vec(Inventory)], ['query']),
  'getAllMessEntries' : IDL.Func([], [IDL.Vec(MessEntry)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getAllSettings' : IDL.Func([], [IDL.Vec(Setting)], ['query']),
  'getAllStudentCounts' : IDL.Func([], [IDL.Vec(StudentCount)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyReport' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalCost' : IDL.Float64,
          'entries' : IDL.Vec(MessEntry),
          'studentCount' : IDL.Opt(StudentCount),
        }),
      ],
      ['query'],
    ),
  'getGroceryConsumptionReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Inventory)],
      ['query'],
    ),
  'getInventoryByItemName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Inventory)],
      ['query'],
    ),
  'getMessEntriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MessEntry)],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'entriesByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
          'totalExpense' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getPurchasesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Purchase)],
      ['query'],
    ),
  'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
  'getStudentCountsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentCount)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFoodCategory' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
  'updateInventory' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateMessEntry' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'updatePurchase' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateStudentCount' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'updateUser' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FoodCategory = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Time = IDL.Int;
  const Inventory = IDL.Record({
    'id' : IDL.Principal,
    'quantityPurchased' : IDL.Float64,
    'remainingStock' : IDL.Float64,
    'unit' : IDL.Text,
    'updatedAt' : Time,
    'itemName' : IDL.Text,
    'quantityUsed' : IDL.Float64,
  });
  const MessEntry = IDL.Record({
    'id' : IDL.Principal,
    'date' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'unit' : IDL.Text,
    'totalCost' : IDL.Float64,
    'pricePerUnit' : IDL.Float64,
    'itemName' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const Purchase = IDL.Record({
    'id' : IDL.Principal,
    'totalPurchase' : IDL.Float64,
    'supplier' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Time,
    'unit' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'itemName' : IDL.Text,
    'quantity' : IDL.Float64,
  });
  const Setting = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text });
  const StudentCount = IDL.Record({
    'id' : IDL.Principal,
    'date' : IDL.Text,
    'studentsOnLeave' : IDL.Nat,
    'createdAt' : Time,
    'totalStudents' : IDL.Nat,
    'studentsPresent' : IDL.Nat,
    'perStudentCost' : IDL.Float64,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFoodCategory' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Principal], []),
    'createInventory' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Principal],
        [],
      ),
    'createMessEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
        [IDL.Principal],
        [],
      ),
    'createPurchase' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
        [IDL.Principal],
        [],
      ),
    'createStudentCount' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [IDL.Principal],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Principal], []),
    'deleteFoodCategory' : IDL.Func([IDL.Principal], [], []),
    'deleteInventory' : IDL.Func([IDL.Principal], [], []),
    'deleteMessEntry' : IDL.Func([IDL.Principal], [], []),
    'deletePurchase' : IDL.Func([IDL.Principal], [], []),
    'deleteStudentCount' : IDL.Func([IDL.Principal], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getAllFoodCategories' : IDL.Func([], [IDL.Vec(FoodCategory)], ['query']),
    'getAllInventory' : IDL.Func([], [IDL.Vec(Inventory)], ['query']),
    'getAllMessEntries' : IDL.Func([], [IDL.Vec(MessEntry)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getAllSettings' : IDL.Func([], [IDL.Vec(Setting)], ['query']),
    'getAllStudentCounts' : IDL.Func([], [IDL.Vec(StudentCount)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyReport' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalCost' : IDL.Float64,
            'entries' : IDL.Vec(MessEntry),
            'studentCount' : IDL.Opt(StudentCount),
          }),
        ],
        ['query'],
      ),
    'getGroceryConsumptionReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Inventory)],
        ['query'],
      ),
    'getInventoryByItemName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Inventory)],
        ['query'],
      ),
    'getMessEntriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MessEntry)],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'entriesByCategory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
            'totalExpense' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getPurchasesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Purchase)],
        ['query'],
      ),
    'getSetting' : IDL.Func([IDL.Text], [IDL.Opt(Setting)], ['query']),
    'getStudentCountsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentCount)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFoodCategory' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateInventory' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateMessEntry' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'updatePurchase' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'updateSetting' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateStudentCount' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updateUser' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };