/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FoodCategory {
  'id' : Principal,
  'name' : string,
  'isActive' : boolean,
}
export interface Inventory {
  'id' : Principal,
  'quantityPurchased' : number,
  'remainingStock' : number,
  'unit' : string,
  'updatedAt' : Time,
  'itemName' : string,
  'quantityUsed' : number,
}
export interface MessEntry {
  'id' : Principal,
  'date' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'unit' : string,
  'totalCost' : number,
  'pricePerUnit' : number,
  'itemName' : string,
  'quantity' : number,
}
export interface Purchase {
  'id' : Principal,
  'totalPurchase' : number,
  'supplier' : string,
  'date' : string,
  'createdAt' : Time,
  'unit' : string,
  'pricePerUnit' : number,
  'itemName' : string,
  'quantity' : number,
}
export interface Setting { 'key' : string, 'value' : string }
export interface StudentCount {
  'id' : Principal,
  'date' : string,
  'studentsOnLeave' : bigint,
  'createdAt' : Time,
  'totalStudents' : bigint,
  'studentsPresent' : bigint,
  'perStudentCost' : number,
}
export type Time = bigint;
export interface User {
  'id' : Principal,
  'username' : string,
  'createdAt' : Time,
  'role' : string,
}
export interface UserProfile { 'username' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFoodCategory' : ActorMethod<[string, boolean], Principal>,
  'createInventory' : ActorMethod<[string, number, number, string], Principal>,
  'createMessEntry' : ActorMethod<
    [string, string, number, string, number],
    Principal
  >,
  'createPurchase' : ActorMethod<
    [string, string, string, number, string, number],
    Principal
  >,
  'createStudentCount' : ActorMethod<
    [string, bigint, bigint, number],
    Principal
  >,
  'createUser' : ActorMethod<[string, string], Principal>,
  'deleteFoodCategory' : ActorMethod<[Principal], undefined>,
  'deleteInventory' : ActorMethod<[Principal], undefined>,
  'deleteMessEntry' : ActorMethod<[Principal], undefined>,
  'deletePurchase' : ActorMethod<[Principal], undefined>,
  'deleteStudentCount' : ActorMethod<[Principal], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getAllFoodCategories' : ActorMethod<[], Array<FoodCategory>>,
  'getAllInventory' : ActorMethod<[], Array<Inventory>>,
  'getAllMessEntries' : ActorMethod<[], Array<MessEntry>>,
  'getAllPurchases' : ActorMethod<[], Array<Purchase>>,
  'getAllSettings' : ActorMethod<[], Array<Setting>>,
  'getAllStudentCounts' : ActorMethod<[], Array<StudentCount>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyReport' : ActorMethod<
    [string],
    {
      'totalCost' : number,
      'entries' : Array<MessEntry>,
      'studentCount' : [] | [StudentCount],
    }
  >,
  'getGroceryConsumptionReport' : ActorMethod<
    [string, string],
    Array<Inventory>
  >,
  'getInventoryByItemName' : ActorMethod<[string], [] | [Inventory]>,
  'getMessEntriesByDate' : ActorMethod<[string], Array<MessEntry>>,
  'getMonthlyReport' : ActorMethod<
    [string, string],
    { 'entriesByCategory' : Array<[string, number]>, 'totalExpense' : number }
  >,
  'getPurchasesByDateRange' : ActorMethod<[string, string], Array<Purchase>>,
  'getSetting' : ActorMethod<[string], [] | [Setting]>,
  'getStudentCountsByDate' : ActorMethod<[string], Array<StudentCount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFoodCategory' : ActorMethod<[Principal, string, boolean], undefined>,
  'updateInventory' : ActorMethod<
    [Principal, string, number, number, string],
    undefined
  >,
  'updateMessEntry' : ActorMethod<
    [Principal, string, string, number, string, number],
    undefined
  >,
  'updatePurchase' : ActorMethod<
    [Principal, string, string, string, number, string, number],
    undefined
  >,
  'updateSetting' : ActorMethod<[string, string], undefined>,
  'updateStudentCount' : ActorMethod<
    [Principal, string, bigint, bigint, number],
    undefined
  >,
  'updateUser' : ActorMethod<[Principal, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];