/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface StudentCount {
    id: Principal;
    date: string;
    studentsOnLeave: bigint;
    createdAt: Time;
    totalStudents: bigint;
    studentsPresent: bigint;
    perStudentCost: number;
}
export interface Inventory {
    id: Principal;
    quantityPurchased: number;
    remainingStock: number;
    unit: string;
    updatedAt: Time;
    itemName: string;
    quantityUsed: number;
}
export interface User {
    id: Principal;
    username: string;
    createdAt: Time;
    role: string;
}
export interface MessEntry {
    id: Principal;
    date: string;
    createdAt: Time;
    createdBy: Principal;
    unit: string;
    totalCost: number;
    pricePerUnit: number;
    itemName: string;
    quantity: number;
}
export interface Setting {
    key: string;
    value: string;
}
export interface Purchase {
    id: Principal;
    totalPurchase: number;
    supplier: string;
    date: string;
    createdAt: Time;
    unit: string;
    pricePerUnit: number;
    itemName: string;
    quantity: number;
}
export interface UserProfile {
    username: string;
    role: string;
}
export interface FoodCategory {
    id: Principal;
    name: string;
    isActive: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFoodCategory(name: string, isActive: boolean): Promise<Principal>;
    createInventory(itemName: string, quantityPurchased: number, quantityUsed: number, unit: string): Promise<Principal>;
    createMessEntry(date: string, itemName: string, quantity: number, unit: string, pricePerUnit: number): Promise<Principal>;
    createPurchase(date: string, supplier: string, itemName: string, quantity: number, unit: string, pricePerUnit: number): Promise<Principal>;
    createStudentCount(date: string, totalStudents: bigint, studentsPresent: bigint, perStudentCost: number): Promise<Principal>;
    createUser(username: string, role: string): Promise<Principal>;
    deleteFoodCategory(categoryId: Principal): Promise<void>;
    deleteInventory(inventoryId: Principal): Promise<void>;
    deleteMessEntry(entryId: Principal): Promise<void>;
    deletePurchase(purchaseId: Principal): Promise<void>;
    deleteStudentCount(countId: Principal): Promise<void>;
    deleteUser(userId: Principal): Promise<void>;
    getAllFoodCategories(): Promise<Array<FoodCategory>>;
    getAllInventory(): Promise<Array<Inventory>>;
    getAllMessEntries(): Promise<Array<MessEntry>>;
    getAllPurchases(): Promise<Array<Purchase>>;
    getAllSettings(): Promise<Array<Setting>>;
    getAllStudentCounts(): Promise<Array<StudentCount>>;
    getAllUsers(): Promise<Array<User>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyReport(date: string): Promise<{
        totalCost: number;
        entries: Array<MessEntry>;
        studentCount?: StudentCount;
    }>;
    getGroceryConsumptionReport(month: string, year: string): Promise<Array<Inventory>>;
    getInventoryByItemName(itemName: string): Promise<Inventory | null>;
    getMessEntriesByDate(date: string): Promise<Array<MessEntry>>;
    getMonthlyReport(month: string, year: string): Promise<{
        entriesByCategory: Array<[string, number]>;
        totalExpense: number;
    }>;
    getPurchasesByDateRange(startDate: string, endDate: string): Promise<Array<Purchase>>;
    getSetting(key: string): Promise<Setting | null>;
    getStudentCountsByDate(date: string): Promise<Array<StudentCount>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateFoodCategory(categoryId: Principal, name: string, isActive: boolean): Promise<void>;
    updateInventory(inventoryId: Principal, itemName: string, quantityPurchased: number, quantityUsed: number, unit: string): Promise<void>;
    updateMessEntry(entryId: Principal, date: string, itemName: string, quantity: number, unit: string, pricePerUnit: number): Promise<void>;
    updatePurchase(purchaseId: Principal, date: string, supplier: string, itemName: string, quantity: number, unit: string, pricePerUnit: number): Promise<void>;
    updateSetting(key: string, value: string): Promise<void>;
    updateStudentCount(countId: Principal, date: string, totalStudents: bigint, studentsPresent: bigint, perStudentCost: number): Promise<void>;
    updateUser(userId: Principal, username: string, role: string): Promise<void>;
}
import type { Inventory as _Inventory, MessEntry as _MessEntry, Setting as _Setting, StudentCount as _StudentCount, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFoodCategory(arg0: string, arg1: boolean): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createFoodCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFoodCategory(arg0, arg1);
            return result;
        }
    }
    async createInventory(arg0: string, arg1: number, arg2: number, arg3: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createMessEntry(arg0: string, arg1: string, arg2: number, arg3: string, arg4: number): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createMessEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMessEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createPurchase(arg0: string, arg1: string, arg2: string, arg3: number, arg4: string, arg5: number): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchase(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchase(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createStudentCount(arg0: string, arg1: bigint, arg2: bigint, arg3: number): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentCount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentCount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async deleteFoodCategory(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodCategory(arg0);
            return result;
        }
    }
    async deleteInventory(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventory(arg0);
            return result;
        }
    }
    async deleteMessEntry(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessEntry(arg0);
            return result;
        }
    }
    async deletePurchase(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchase(arg0);
            return result;
        }
    }
    async deleteStudentCount(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentCount(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getAllFoodCategories(): Promise<Array<FoodCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodCategories();
            return result;
        }
    }
    async getAllInventory(): Promise<Array<Inventory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventory();
            return result;
        }
    }
    async getAllMessEntries(): Promise<Array<MessEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessEntries();
            return result;
        }
    }
    async getAllPurchases(): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchases();
            return result;
        }
    }
    async getAllSettings(): Promise<Array<Setting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSettings();
            return result;
        }
    }
    async getAllStudentCounts(): Promise<Array<StudentCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentCounts();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyReport(arg0: string): Promise<{
        totalCost: number;
        entries: Array<MessEntry>;
        studentCount?: StudentCount;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyReport(arg0);
                return from_candid_record_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyReport(arg0);
            return from_candid_record_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroceryConsumptionReport(arg0: string, arg1: string): Promise<Array<Inventory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroceryConsumptionReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroceryConsumptionReport(arg0, arg1);
            return result;
        }
    }
    async getInventoryByItemName(arg0: string): Promise<Inventory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryByItemName(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryByItemName(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessEntriesByDate(arg0: string): Promise<Array<MessEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessEntriesByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessEntriesByDate(arg0);
            return result;
        }
    }
    async getMonthlyReport(arg0: string, arg1: string): Promise<{
        entriesByCategory: Array<[string, number]>;
        totalExpense: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return result;
        }
    }
    async getPurchasesByDateRange(arg0: string, arg1: string): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchasesByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchasesByDateRange(arg0, arg1);
            return result;
        }
    }
    async getSetting(arg0: string): Promise<Setting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetting(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetting(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentCountsByDate(arg0: string): Promise<Array<StudentCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentCountsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentCountsByDate(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateFoodCategory(arg0: Principal, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFoodCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFoodCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async updateInventory(arg0: Principal, arg1: string, arg2: number, arg3: number, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventory(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventory(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateMessEntry(arg0: Principal, arg1: string, arg2: string, arg3: number, arg4: string, arg5: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMessEntry(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMessEntry(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePurchase(arg0: Principal, arg1: string, arg2: string, arg3: string, arg4: number, arg5: string, arg6: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchase(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateSetting(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSetting(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSetting(arg0, arg1);
            return result;
        }
    }
    async updateStudentCount(arg0: Principal, arg1: string, arg2: bigint, arg3: bigint, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentCount(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentCount(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateUser(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentCount]): StudentCount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Inventory]): Inventory | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Setting]): Setting | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCost: number;
    entries: Array<_MessEntry>;
    studentCount: [] | [_StudentCount];
}): {
    totalCost: number;
    entries: Array<MessEntry>;
    studentCount?: StudentCount;
} {
    return {
        totalCost: value.totalCost,
        entries: value.entries,
        studentCount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.studentCount))
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
